@FractalLab.Server.MainWebApp_HostAddress = http://localhost:5165

GET {{FractalLab.Server.MainWebApp_HostAddress}}/todos/
Accept: application/json

###

GET {{FractalLab.Server.MainWebApp_HostAddress}}/todos/1
Accept: application/json

###

GET {{FractalLab.Server.MainWebApp_HostAddress}}/fractal/mandelbrot-set

###

GET {{FractalLab.Server.MainWebApp_HostAddress}}/fractal/mandelbrot-set/{xMin}/{xMax}/{yMin}/{yMax}/{width}/{height}/{maxIterations}/{provider}

###

GET {{FractalLab.Server.MainWebApp_HostAddress}}/fractal

###

GET {{FractalLab.Server.MainWebApp_HostAddress}}/

###
